FROM group4-airflow:2.7.3-spark-base

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        procps \
        openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER airflow

RUN pip install --no-cache-dir \
    "Flask-Session==0.5.0" \
    "SQLAlchemy==1.4.50" \
    "pendulum==2.1.2"
