ARG SPARK_IMAGE
FROM ${SPARK_IMAGE}

USER root

COPY requirements.txt /tmp/requirements.txt

RUN /opt/bitnami/python/bin/python3 -m pip install \
    --no-cache-dir \
    --default-timeout=120 \
    --retries=5 \
    --index-url https://pypi.org/simple \
    -r /tmp/requirements.txt

ENV PATH="/opt/bitnami/python/bin:${PATH}"

USER 1001
